# Generated by Django 4.0.9 on 2023-02-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priece',
            new_name='price',
        ),
    ]
