# Generated by Django 4.0.9 on 2023-05-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('consola', 'consola'), ('edicion', 'edicion')], max_length=100),
        ),
    ]
